/*
    CODED BY WAYNE 10/11/2018
    CISO OFFICE @ GADTC
    MALORO, TANGUB CITY
    --This is for educational reference only.
    SAMPLE USING JFRAME PROJECT



---GUI was created by CABRERA, POGI
---CRITICS BY SAMUEL CARUMBA
 */


package ordersystem;

import com.bulenkov.darcula.DarculaLaf;
//import com.sun.security.sasl.util.PolicyUtils;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicLookAndFeel;

/**
 *
 * @author Wayne
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    double totalBill = 0;
    
    
    public NewJFrame() {
        initComponents();
        
        
        jtxtDiscount.setText("0.0");
        jtxtBill.setText("0.0");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtDiscount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        BtnChange = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        jtxtBill = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        checkBoxTshirt = new javax.swing.JCheckBox();
        checkBoxPoloshirt = new javax.swing.JCheckBox();
        checkBoxPolo = new javax.swing.JCheckBox();
        checkBoxLJacket = new javax.swing.JCheckBox();
        checkBoxJeans = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtAmountDue = new javax.swing.JTextField();
        btnPayNow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bill:");

        jLabel2.setText("Discount:");

        jtxtDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDiscountKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Total Amount:");

        jtxtAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setText("Change:");

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        BtnChange.setText("CALCULATE");
        BtnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChangeActionPerformed(evt);
            }
        });

        BtnNext.setText("CLEAR");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        jtxtBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        checkBoxTshirt.setText("Tshirt");
        checkBoxTshirt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxTshirtItemStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxTshirt);
        checkBoxTshirt.setBounds(21, 15, 111, 24);

        checkBoxPoloshirt.setText("Polo Shirt");
        checkBoxPoloshirt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxPoloshirtItemStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxPoloshirt);
        checkBoxPoloshirt.setBounds(21, 75, 111, 24);

        checkBoxPolo.setText("Polo");
        checkBoxPolo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxPoloItemStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxPolo);
        checkBoxPolo.setBounds(21, 103, 111, 24);

        checkBoxLJacket.setText("Leather Jacket");
        checkBoxLJacket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxLJacketItemStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxLJacket);
        checkBoxLJacket.setBounds(21, 133, 161, 24);

        checkBoxJeans.setText("Jeans");
        checkBoxJeans.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxJeansItemStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxJeans);
        checkBoxJeans.setBounds(21, 45, 111, 24);

        jLabel5.setText("199.75");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(188, 19, 78, 16);

        jLabel6.setText("499.75");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(188, 49, 38, 16);

        jLabel7.setText("399.75");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(188, 79, 38, 16);

        jLabel8.setText("299.75");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(188, 107, 38, 16);

        jLabel9.setText("1599.75");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(188, 133, 45, 16);

        jLabel10.setText("Amount Due:");

        jtxtAmountDue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnPayNow.setText("PAY NOW");
        btnPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtxtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jtxtAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNext)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnChange)
                            .addComponent(BtnNext))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        // TODO add your handling code here:
        jtxtChange.setText("");
        jtxtAmount.setText("0.0");
        jtxtDiscount.setText("");
      
        jtxtBill.setText("0.0");
        jtxtAmountDue.setText("0.0");
        
        checkBoxPolo.setSelected(false);
        checkBoxTshirt.setSelected(false);
        checkBoxPoloshirt.setSelected(false);
        checkBoxJeans.setSelected(false);
        checkBoxLJacket.setSelected(false);
        
        totalBill = 0;
    }//GEN-LAST:event_BtnNextActionPerformed

    private void checkBoxTshirtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxTshirtItemStateChanged
        // TODO add your handling code here:
        if(checkBoxTshirt.isSelected()){
            totalBill += 199.75;
        }else{
             totalBill -= 199.75;
        }
        
        jtxtBill.setText(String.valueOf(totalBill));
         
    }//GEN-LAST:event_checkBoxTshirtItemStateChanged

    private void checkBoxJeansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxJeansItemStateChanged
        // TODO add your handling code here:
        if(checkBoxJeans.isSelected()){
            totalBill += 499.75; 
        }else{
             totalBill -= 499.75;
        }
         
        jtxtBill.setText(String.valueOf(totalBill));
    }//GEN-LAST:event_checkBoxJeansItemStateChanged

    private void checkBoxPoloshirtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxPoloshirtItemStateChanged
        // TODO add your handling code here:
        if(checkBoxPoloshirt.isSelected()){
            totalBill += 399.75; 
        }else{
             totalBill -= 399.75;
        }
        jtxtBill.setText(String.valueOf(totalBill));
    }//GEN-LAST:event_checkBoxPoloshirtItemStateChanged

    private void checkBoxPoloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxPoloItemStateChanged
        // TODO add your handling code here:
        if(checkBoxPolo.isSelected()){
            totalBill += 299.75; 
        }else{
             totalBill -= 299.75;
        }
        
        jtxtBill.setText(String.valueOf(totalBill));
    }//GEN-LAST:event_checkBoxPoloItemStateChanged

    private void checkBoxLJacketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxLJacketItemStateChanged
        // TODO add your handling code here:
        if(checkBoxLJacket.isSelected()){
            totalBill += 1599.75; 
        }else{
             totalBill -= 1599.75;
        }
        
        jtxtBill.setText(String.valueOf(totalBill));
    }//GEN-LAST:event_checkBoxLJacketItemStateChanged

    private void BtnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChangeActionPerformed
        // TODO add your handling code here:
        if(Double.parseDouble(jtxtBill.getText())  < 1){
            warnBox("SELECT PPRODUCT!", "Please select product.");
            return;
        }
        
       double totalAmount = 0;
       double discount = Double.parseDouble(jtxtDiscount.getText());
       discount =  Double.parseDouble(jtxtBill.getText()) - (Double.parseDouble(jtxtBill.getText()) * (discount/100));
       jtxtAmountDue.setText(String.valueOf(discount));
       
        
    }//GEN-LAST:event_BtnChangeActionPerformed

    private void jtxtDiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDiscountKeyPressed
        // TODO add your handling code here:
        
        /*int key = evt.getKeyCode();*/

            /* Restrict input to only integers 
          if (key < 96 && key > 105){
             // evt.setKeyChar("");
             evt.setKeyChar('a');
             return;
          }*/
          
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
              evt.consume();
        }      
    }//GEN-LAST:event_jtxtDiscountKeyPressed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
        // TODO add your handling code here:
        //if(jtxtAmount.)
        double change = Double.parseDouble(jtxtAmount.getText()) - Double.parseDouble(jtxtAmountDue.getText());
        jtxtChange.setText(String.valueOf(change));
    }//GEN-LAST:event_btnPayNowActionPerformed

    
    
    void infoBox(String title, String msg){
        JOptionPane.showMessageDialog(null, msg, "InfoBox: " + title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    void warnBox(String title, String msg){
        JOptionPane.showMessageDialog(null, msg, "Warning: " + title, JOptionPane.WARNING_MESSAGE);
    }
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            BasicLookAndFeel darcula = new DarculaLaf();
            UIManager.setLookAndFeel(darcula);
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Darcula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //BasicLookAndFeel darcula = new DarculaLaf();
        //UIManager.setLookAndFeel(darcula);
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChange;
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JCheckBox checkBoxJeans;
    private javax.swing.JCheckBox checkBoxLJacket;
    private javax.swing.JCheckBox checkBoxPolo;
    private javax.swing.JCheckBox checkBoxPoloshirt;
    private javax.swing.JCheckBox checkBoxTshirt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtAmountDue;
    private javax.swing.JTextField jtxtBill;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDiscount;
    // End of variables declaration//GEN-END:variables
}
